version: '3.7'

services:
  nextjs:
    build: .
    ports:
      - '3000:3000'

  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - nextjs
